### ISSUE TITLE
Redirects 

### ISSUE THREAD

**Issue by mohdaljaraba** [soderlind/customizer-polylang#15]
After i active the code all my links redirects to the main language ex: the main language website.com and the 2nd language website.com/en if i create all pages under /en/ will redirects to website.com/ kid of deleting language code /en/

**Comment by erikyo** [comment]
@mohdaljaraba I had the same problem too and made a pull request to solve the problem! 

https://github.com/soderlind/customizer-polylang/pull/19

I think the issue is (probably) that we don't want to be redirected only when we're in the wp-customizer, but by doing so (code below) a rule was made that works globally, even in the front-end which is probably not needed.

`$options = get_option( 'polylang' );
if ( isset( $options['force_lang'] ) && 0 !== $options['force_lang'] ) {
	$options['force_lang'] = 0;
	update_option( 'polylang', $options );
}
/**
* Disable detect browser language, will return default language instead.
*/
add_filter( 'pll_preferred_language', '__return_false' );`

if you can try the code of my pull request, you will do me a favor. Remember after change the code you have to go to polylang -> settings and change to your liking "language detection" and "URL modifications". then update permalinks

**Comment by soderlind** [comment]
fixed, see #19
